# Generated by Django 5.1.1 on 2024-10-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinop", "0002_rename_raiting_movie_rating_remove_movie_director_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="media_type",
        ),
        migrations.AddField(
            model_name="movie",
            name="media_type",
            field=models.ManyToManyField(
                null=True, to="kinop.mediatype", verbose_name="Тип медиа"
            ),
        ),
    ]
