# Generated by Django 5.1.1 on 2024-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinop", "0003_remove_movie_media_type_movie_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="media_type",
            field=models.ManyToManyField(
                to="kinop.mediatype", verbose_name="Тип медиа"
            ),
        ),
    ]
