# Generated by Django 5.1.1 on 2024-10-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinop", "0004_alter_movie_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(to="kinop.director"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="kinop.genre"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="movies", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="media_type",
            field=models.ManyToManyField(to="kinop.mediatype"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.FloatField(verbose_name="Рейтинг"),
        ),
    ]
